using System.Net.Http.Headers; using System.Net.Http.Json; using System.Text.Json; using ResearchTrack.BuildingBlocks.Api.Constants; using ResearchTrack.BuildingBlocks.Api.Exceptions; using ResearchTrack.JiraService.Configuration; using ResearchTrack.JiraService.Contracts;
namespace ResearchTrack.JiraService.Infrastructure;
public sealed class AtlassianClient
{
    private readonly HttpClient _http; private readonly JiraOptions _options;
    public AtlassianClient(HttpClient http, JiraOptions options){_http=http;_options=options;}
    public async Task<TokenResult> ExchangeCodeAsync(string code,CancellationToken ct){ using var response=await _http.PostAsJsonAsync(_options.TokenUrl,new {grant_type="authorization_code",client_id=_options.ClientId,client_secret=_options.ClientSecret,code,redirect_uri=_options.RedirectUri},ct); if(!response.IsSuccessStatusCode) throw Failure("Atlassian authorization could not be completed."); using var doc=JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct)); var r=doc.RootElement; var access=GetString(r,"access_token") ?? throw Failure("Atlassian returned no access token."); var refresh=GetString(r,"refresh_token"); var scope=GetString(r,"scope"); DateTimeOffset? expires=null; if(r.TryGetProperty("expires_in",out var e)&&e.TryGetInt32(out var seconds)) expires=DateTimeOffset.UtcNow.AddSeconds(seconds); return new(access,refresh,expires,scope); }
    public async Task<IReadOnlyList<JiraWorkspaceOption>> GetWorkspacesAsync(string token,CancellationToken ct){ using var req=Authorized(HttpMethod.Get,_options.AccessibleResourcesUrl,token); using var res=await _http.SendAsync(req,ct); if(!res.IsSuccessStatusCode) throw Failure("Unable to load Jira workspaces."); var items=JsonDocument.Parse(await res.Content.ReadAsStringAsync(ct)).RootElement; var list=new List<JiraWorkspaceOption>(); foreach(var x in items.EnumerateArray()){var id=GetString(x,"id");var name=GetString(x,"name"); if(id is not null&&name is not null) list.Add(new(id,name,GetString(x,"url")));} if(list.Count==0) throw Failure("No accessible Jira workspace was returned."); return list; }
    public async Task<IReadOnlyList<JiraProjectOption>> GetProjectsAsync(string token,string cloudId,CancellationToken ct){ var list=new List<JiraProjectOption>(); var start=0; while(true){using var req=Authorized(HttpMethod.Get,$"{_options.ApiBaseUrl.TrimEnd('/')}/ex/jira/{Uri.EscapeDataString(cloudId)}/rest/api/3/project/search?startAt={start}&maxResults=50&orderBy=name",token); using var res=await _http.SendAsync(req,ct); if(!res.IsSuccessStatusCode) throw Failure("Unable to load accessible Jira projects."); using var doc=JsonDocument.Parse(await res.Content.ReadAsStringAsync(ct)); var root=doc.RootElement; if(!root.TryGetProperty("values",out var values)) break; foreach(var x in values.EnumerateArray()){var id=GetString(x,"id");var key=GetString(x,"key");var name=GetString(x,"name");if(id is not null&&key is not null&&name is not null)list.Add(new(id,key,name));} var total=root.TryGetProperty("total",out var t)&&t.TryGetInt32(out var n)?n:list.Count; start+=values.GetArrayLength(); if(start>=total||values.GetArrayLength()==0)break;} return list; }
    public async Task<IReadOnlyList<JiraBoardOption>> GetBoardsAsync(string token,string cloudId,string projectKeyOrId,CancellationToken ct){ using var req=Authorized(HttpMethod.Get,$"{_options.ApiBaseUrl.TrimEnd('/')}/ex/jira/{Uri.EscapeDataString(cloudId)}/rest/agile/1.0/board?projectKeyOrId={Uri.EscapeDataString(projectKeyOrId)}&maxResults=50",token); using var res=await _http.SendAsync(req,ct); if(!res.IsSuccessStatusCode) throw Failure("Unable to load Jira boards for the selected project."); using var doc=JsonDocument.Parse(await res.Content.ReadAsStringAsync(ct)); var list=new List<JiraBoardOption>(); if(doc.RootElement.TryGetProperty("values",out var values)) foreach(var x in values.EnumerateArray()) if(x.TryGetProperty("id",out var i)&&i.TryGetInt64(out var id)){var name=GetString(x,"name")??$"Board {id}";var type=GetString(x,"type")??"unknown";list.Add(new(id,name,type));} return list; }
    private static HttpRequestMessage Authorized(HttpMethod method,string url,string token){var r=new HttpRequestMessage(method,url);r.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);r.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));return r;}
    private static string? GetString(JsonElement e,string n)=>e.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.String?p.GetString():null;
    private static ApiException Failure(string m)=>new(400,ErrorCodes.ValidationError,m);
    public sealed record TokenResult(string AccessToken,string? RefreshToken,DateTimeOffset? ExpiresAt,string? Scope);
}
