// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ResearchTrack.ProjectService.Persistence;

#nullable disable

namespace ResearchTrack.ProjectService.Persistence.Migrations;

[DbContext(typeof(ProjectDbContext))]
partial class ProjectDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("ResearchTrack.ProjectService.Domain.Project", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedNever().HasColumnType("char(36)");
            b.Property<string>("Batch").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
            b.Property<string>("LifecycleStatus").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
            b.Property<int>("ProgressPercent").HasColumnType("int");
            b.Property<string>("Semester").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
            b.Property<string>("Summary").IsRequired().HasMaxLength(250).HasColumnType("varchar(250)");
            b.Property<Guid>("SupervisorUserId").HasColumnType("char(36)");
            b.Property<string>("Title").IsRequired().HasMaxLength(40).HasColumnType("varchar(40)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime(6)");
            b.HasKey("Id");
            b.HasIndex("SupervisorUserId").HasDatabaseName("ix_projects_supervisor_user_id");
            b.HasIndex("SupervisorUserId", "CreatedAt").HasDatabaseName("ix_projects_supervisor_created_at");
            b.ToTable("projects", (string)null);
        });
#pragma warning restore 612, 618
    }
}
