// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchTrack.GitHubService.Persistence;

#nullable disable

namespace ResearchTrack.GitHubService.Persistence.Migrations
{
    [DbContext(typeof(GitHubDbContext))]
    partial class GitHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.GitHubAccessSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ActiveInstallationKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveInstallationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_github_access_sources_active_installation");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_github_access_sources_project_id");

                    b.ToTable("github_access_sources", (string)null);
                });


            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.GitHubAccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AuthorizationStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PendingProjectKey")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TargetOwnerLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResultNonce")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ResultTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TokenNonce")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_github_access_requests_expires_at");

                    b.HasIndex("PendingProjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_github_access_requests_pending_project");

                    b.HasIndex("ResultTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_github_access_requests_result_token_hash");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_github_access_requests_token_hash");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("ix_github_access_requests_project_status");

                    b.ToTable("github_access_requests", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.GitHubInstallationFlowState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AccessRequestId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AuthorizationStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("InitiatingUserId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("PendingInstallationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReturnPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AccessRequestId")
                        .HasDatabaseName("ix_github_installation_flow_states_access_request");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_github_installation_flow_states_expires_at");

                    b.HasIndex("StateHash")
                        .IsUnique()
                        .HasDatabaseName("ux_github_installation_flow_states_hash");

                    b.HasIndex("ProjectId", "InitiatingUserId")
                        .HasDatabaseName("ix_github_installation_flow_states_project_user");

                    b.ToTable("github_installation_flow_states", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.GitHubRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long>("GitHubRepositoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OwnerLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubRepositoryId")
                        .HasDatabaseName("ix_github_repositories_github_id");

                    b.HasIndex("SourceId", "GitHubRepositoryId")
                        .IsUnique()
                        .HasDatabaseName("ux_github_repositories_source_github_id");

                    b.ToTable("github_repositories", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.GitHubWebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<long?>("GitHubRepositoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InstallationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId")
                        .IsUnique()
                        .HasDatabaseName("ux_github_webhook_deliveries_delivery_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_github_webhook_deliveries_received_at");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_github_webhook_deliveries_status_next_attempt");

                    b.ToTable("github_webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.ProjectRepositoryLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CustomName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long>("GitHubRepoId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GitHubRepositoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("LastFailedSyncAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastKnownHeadSha")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("LastSyncStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LinkedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OwnerLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Primary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PrimaryProjectKey")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubRepositoryId");

                    b.HasIndex("PrimaryProjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_project_repository_links_primary_project");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_project_repository_links_source_id");

                    b.HasIndex("ProjectId", "Active")
                        .HasDatabaseName("ix_project_repository_links_project_active");

                    b.ToTable("project_repository_links", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.GitHubRepository", b =>
                {
                    b.HasOne("ResearchTrack.GitHubService.Domain.GitHubAccessSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResearchTrack.GitHubService.Domain.ProjectRepositoryLink", b =>
                {
                    b.HasOne("ResearchTrack.GitHubService.Domain.GitHubRepository", null)
                        .WithMany()
                        .HasForeignKey("GitHubRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResearchTrack.GitHubService.Domain.GitHubAccessSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
