#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/env.sh"
rt_cd_root
rt_require_command dotnet

configuration="${CONFIGURATION:-Release}"
run_tests=true
no_build=false
for arg in "$@"; do
  case "$arg" in
    --no-test) run_tests=false ;;
    --no-build) no_build=true ;;
    *)
      echo "Usage: ./scripts/coverage.sh [--no-test] [--no-build]" >&2
      exit 1
      ;;
  esac
done

coverage_root="${COVERAGE_OUTPUT_DIR:-artifacts/coverage}"
test_results_root="${UNIT_TEST_RESULTS_DIR:-artifacts/test-results/unit}"
raw_results_dir="${test_results_root}/raw"
report_dir="${coverage_root}/report"

rm -rf "$coverage_root" "$test_results_root"
mkdir -p "$raw_results_dir" "$report_dir"

echo "==> Restoring local .NET tools"
dotnet tool restore

if [[ "$run_tests" == true ]]; then
  echo "==> Running unit + mocked tests with coverage"
  test_args=(
    ResearchTrack.sln
    -c "$configuration"
    --filter "Category!=DatabaseIntegration"
    --collect:"XPlat Code Coverage"
    --results-directory "$raw_results_dir"
  )
  if [[ "$no_build" == true ]]; then
    test_args+=(--no-build)
  fi
  dotnet test "${test_args[@]}"
fi

if [[ "$run_tests" == true ]]; then
  mapfile -t reports < <(find "$raw_results_dir" -type f -name 'coverage.cobertura.xml' 2>/dev/null | sort -u)
else
  mapfile -t reports < <(find tests artifacts/test-results -type f -name 'coverage.cobertura.xml' 2>/dev/null | sort -u)
fi
if (( ${#reports[@]} == 0 )); then
  echo "No coverage.cobertura.xml files were found." >&2
  echo "Run without --no-test, or provide existing coverage results under tests/**/TestResults." >&2
  exit 2
fi

reports_arg="$(IFS=';'; echo "${reports[*]}")"

echo "==> Merging ${#reports[@]} Cobertura report(s)"
dotnet reportgenerator \
  "-reports:${reports_arg}" \
  "-targetdir:${report_dir}" \
  "-reporttypes:Html;Cobertura;MarkdownSummaryGithub;MarkdownAssembliesSummary;JsonSummary;TextSummary;CsvSummary" \
  "-assemblyfilters:+ResearchTrack.*;-*.Tests;-ResearchTrack.Testing;-ResearchTrack.DevSeeder;-ResearchTrack.DbCheck" \
  "-filefilters:-**/Migrations/**;-**/Program.cs;-**/obj/**;-**/*.g.cs"

merged="${report_dir}/Cobertura.xml"
summary="${report_dir}/SummaryGithub.md"
if [[ ! -f "$merged" || ! -f "$summary" ]]; then
  echo "Coverage report generation did not create the expected merged outputs." >&2
  exit 3
fi

python - "$merged" "$coverage_root/coverage-metrics.env" "$coverage_root/coverage-summary.md" <<'PY'
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

xml_path, env_path, md_path = map(Path, sys.argv[1:4])
root = ET.parse(xml_path).getroot()

def pct(attr: str) -> float:
    raw = root.attrib.get(attr, "0")
    try:
        return float(raw) * 100.0
    except ValueError:
        return 0.0

line = pct("line-rate")
branch = pct("branch-rate")
lines_valid = int(root.attrib.get("lines-valid", "0") or 0)
lines_covered = int(root.attrib.get("lines-covered", "0") or 0)
branches_valid = int(root.attrib.get("branches-valid", "0") or 0)
branches_covered = int(root.attrib.get("branches-covered", "0") or 0)

env_path.write_text(
    f"LINE_COVERAGE={line:.2f}\n"
    f"BRANCH_COVERAGE={branch:.2f}\n"
    f"LINES_COVERED={lines_covered}\n"
    f"LINES_VALID={lines_valid}\n"
    f"BRANCHES_COVERED={branches_covered}\n"
    f"BRANCHES_VALID={branches_valid}\n"
)
md_path.write_text(
    "# ResearchTrack Unit-Test Coverage\n\n"
    "| Metric | Result |\n"
    "|---|---:|\n"
    f"| Line coverage | **{line:.2f}%** ({lines_covered}/{lines_valid}) |\n"
    f"| Branch coverage | **{branch:.2f}%** ({branches_covered}/{branches_valid}) |\n\n"
    "> Scope: production ResearchTrack assemblies exercised by tests filtered with `Category!=DatabaseIntegration`. "
    "Generated EF migrations, `Program.cs`, test assemblies, and test infrastructure are excluded from the merged report.\n"
)
print(f"Line coverage:   {line:.2f}% ({lines_covered}/{lines_valid})")
print(f"Branch coverage: {branch:.2f}% ({branches_covered}/{branches_valid})")
PY

# Optional quality gates. They are intentionally opt-in until the team reviews a real baseline.
source "$coverage_root/coverage-metrics.env"
python - "${COVERAGE_MIN_LINE:-}" "${COVERAGE_MIN_BRANCH:-}" "$LINE_COVERAGE" "$BRANCH_COVERAGE" <<'PY'
import sys
min_line, min_branch, line, branch = sys.argv[1:]
checks = []
if min_line:
    checks.append(("line", float(line), float(min_line)))
if min_branch:
    checks.append(("branch", float(branch), float(min_branch)))
failed = [(name, actual, minimum) for name, actual, minimum in checks if actual < minimum]
for name, actual, minimum in checks:
    print(f"Coverage gate {name}: {actual:.2f}% >= {minimum:.2f}% -> {'PASS' if actual >= minimum else 'FAIL'}")
if failed:
    raise SystemExit(4)
PY

cat > "$coverage_root/README.md" <<EOF2
# Generated unit-test coverage evidence

This directory is generated by \`./scripts/coverage.sh\` and is intentionally ignored by Git.

Key files:

- \`coverage-summary.md\` — concise overall line/branch result.
- \`coverage-metrics.env\` — machine-readable metrics used by CI.
- \`report/index.html\` — interactive HTML coverage report.
- \`report/Cobertura.xml\` — merged machine-readable coverage report.
- \`report/SummaryGithub.md\` — GitHub-optimized summary.
- \`report/Summary.md\` — assembly-level summary when generated by ReportGenerator.
- \`report/Summary.json\` / \`report/Summary.txt\` / \`report/Summary.csv\` — additional evidence formats.

No minimum coverage threshold is hard-coded. After reviewing a stable baseline, CI can opt in with \`COVERAGE_MIN_LINE\` and/or \`COVERAGE_MIN_BRANCH\`.
EOF2

echo "==> Coverage evidence generated at ${coverage_root}"
echo "    HTML: ${report_dir}/index.html"
echo "    Summary: ${coverage_root}/coverage-summary.md"
