using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using ResearchTrack.BuildingBlocks.Api.Constants;
using ResearchTrack.BuildingBlocks.Api.Exceptions;
using ResearchTrack.JiraService.Contracts;
using ResearchTrack.JiraService.Domain;
using ResearchTrack.JiraService.Infrastructure;
using ResearchTrack.JiraService.Persistence;
namespace ResearchTrack.JiraService.Features;
public interface IJiraSyncService { Task<JiraSyncResponse> SynchronizeAsync(Guid projectId,CancellationToken ct); }
public sealed class JiraSyncService : IJiraSyncService
{
 private readonly IDbContextFactory<JiraDbContext> _factory; private readonly AtlassianClient _client; private readonly IJiraTokenProtector _protector;
 public JiraSyncService(IDbContextFactory<JiraDbContext> factory,AtlassianClient client,IJiraTokenProtector protector){_factory=factory;_client=client;_protector=protector;}
 public async Task<JiraSyncResponse> SynchronizeAsync(Guid projectId,CancellationToken ct)
 {
  await using var db=await _factory.CreateDbContextAsync(ct);var c=await db.JiraConnections.SingleOrDefaultAsync(x=>x.ResearchProjectId==projectId,ct)??throw new ApiException(400,ErrorCodes.ValidationError,"Jira is not connected for this project.");
  c.SyncStatus="SYNCING";c.LastSyncError=null;c.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);
  try{
   var token=await ValidTokenAsync(db,c,ct);var fields=await _client.GetFieldsAsync(token,c.CloudId,ct);var sp=fields.FirstOrDefault(x=>string.Equals(x.Name,"Story Points",StringComparison.OrdinalIgnoreCase)||string.Equals(x.CustomSchema,"com.pyxis.greenhopper.jira:jsw-story-points",StringComparison.OrdinalIgnoreCase))?.Id;
   var rawIssues=await _client.GetProjectIssuesAsync(token,c.CloudId,c.JiraProjectKey,sp,ct);var now=DateTimeOffset.UtcNow;var existing=await db.JiraIssues.Where(x=>x.ResearchProjectId==projectId).ToDictionaryAsync(x=>x.JiraIssueId,ct);var seen=new HashSet<string>(StringComparer.Ordinal);
   foreach(var raw in rawIssues){var id=S(raw,"id");var key=S(raw,"key");if(id is null||key is null||!raw.TryGetProperty("fields",out var f))continue;seen.Add(id);if(!existing.TryGetValue(id,out var issue)){issue=new JiraIssue{Id=Guid.NewGuid(),JiraConnectionId=c.Id,ResearchProjectId=projectId,JiraIssueId=id};db.JiraIssues.Add(issue);}MapIssue(issue,key,f,sp,now);}
   foreach(var stale in existing.Values.Where(x=>!seen.Contains(x.JiraIssueId)))db.JiraIssues.Remove(stale);
   await db.SaveChangesAsync(ct);
   var issueIds=await db.JiraIssues.Where(x=>x.ResearchProjectId==projectId).ToDictionaryAsync(x=>x.JiraIssueId,x=>x.Id,ct);var sprintCount=0;
   if(c.JiraBoardId.HasValue){var raws=await _client.GetSprintsAsync(token,c.CloudId,c.JiraBoardId.Value,ct);var existingSprints=await db.JiraSprints.Where(x=>x.ResearchProjectId==projectId).ToDictionaryAsync(x=>x.JiraSprintId,ct);var seenSprints=new HashSet<long>();db.JiraIssueSprints.RemoveRange(db.JiraIssueSprints.Where(x=>db.JiraIssues.Where(i=>i.ResearchProjectId==projectId).Select(i=>i.Id).Contains(x.JiraIssueId)));await db.SaveChangesAsync(ct);foreach(var raw in raws){if(!raw.TryGetProperty("id",out var ie)||!ie.TryGetInt64(out var sid))continue;seenSprints.Add(sid);if(!existingSprints.TryGetValue(sid,out var sprint)){sprint=new JiraSprint{Id=Guid.NewGuid(),JiraConnectionId=c.Id,ResearchProjectId=projectId,JiraSprintId=sid,JiraBoardId=c.JiraBoardId.Value};db.JiraSprints.Add(sprint);}sprint.Name=S(raw,"name")??$"Sprint {sid}";sprint.State=S(raw,"state")??"unknown";sprint.Goal=S(raw,"goal");sprint.StartDate=D(raw,"startDate");sprint.EndDate=D(raw,"endDate");sprint.CompleteDate=D(raw,"completeDate");sprint.SyncedAt=now;await db.SaveChangesAsync(ct);var members=await _client.GetSprintIssueIdsAsync(token,c.CloudId,sid,ct);foreach(var member in members)if(issueIds.TryGetValue(member,out var iid))db.JiraIssueSprints.Add(new JiraIssueSprint{JiraIssueId=iid,JiraSprintId=sprint.Id});sprintCount++;}foreach(var stale in existingSprints.Values.Where(x=>!seenSprints.Contains(x.JiraSprintId)))db.JiraSprints.Remove(stale);}
   c.SyncStatus="SYNCED";c.LastSyncedAt=now;c.LastSyncError=null;c.UpdatedAt=now;await db.SaveChangesAsync(ct);return new(seen.Count,sprintCount,now);
  }catch(Exception ex){c.SyncStatus="FAILED";c.LastSyncError=Safe(ex.Message);c.UpdatedAt=DateTimeOffset.UtcNow;await db.SaveChangesAsync(CancellationToken.None);throw;}
 }
 private async Task<string> ValidTokenAsync(JiraDbContext db,JiraConnection c,CancellationToken ct){if(!c.TokenExpiresAt.HasValue||c.TokenExpiresAt.Value>DateTimeOffset.UtcNow.AddMinutes(2))return _protector.Unprotect(c.AccessTokenProtected);if(string.IsNullOrWhiteSpace(c.RefreshTokenProtected))throw new ApiException(401,ErrorCodes.Unauthorized,"Jira authorization has expired. Reconnect Jira.");var refreshed=await _client.RefreshTokenAsync(_protector.Unprotect(c.RefreshTokenProtected),ct);c.AccessTokenProtected=_protector.Protect(refreshed.AccessToken);c.RefreshTokenProtected=_protector.Protect(refreshed.RefreshToken!);c.TokenExpiresAt=refreshed.ExpiresAt;c.Scope=refreshed.Scope??c.Scope;await db.SaveChangesAsync(ct);return refreshed.AccessToken;}
 private static void MapIssue(JiraIssue x,string key,JsonElement f,string? sp,DateTimeOffset now){x.IssueKey=key;x.Summary=S(f,"summary")??"(No summary)";x.DescriptionJson=f.TryGetProperty("description",out var desc)&&desc.ValueKind is not JsonValueKind.Null and not JsonValueKind.Undefined?desc.GetRawText():null;if(f.TryGetProperty("issuetype",out var it)){x.IssueTypeId=S(it,"id");x.IssueTypeName=S(it,"name")??"Unknown";x.IsSubtask=B(it,"subtask");}if(f.TryGetProperty("status",out var st)){x.StatusId=S(st,"id");x.StatusName=S(st,"name")??"Unknown";if(st.TryGetProperty("statusCategory",out var sc)){x.StatusCategoryId=S(sc,"id");x.StatusCategoryKey=S(sc,"key");x.StatusCategoryName=S(sc,"name");}}if(f.TryGetProperty("priority",out var pr)&&pr.ValueKind==JsonValueKind.Object){x.PriorityId=S(pr,"id");x.PriorityName=S(pr,"name");}else{x.PriorityId=null;x.PriorityName=null;}Person(f,"assignee",out var aa,out var an);x.AssigneeAccountId=aa;x.AssigneeDisplayName=an;Person(f,"reporter",out var ra,out var rn);x.ReporterAccountId=ra;x.ReporterDisplayName=rn;if(f.TryGetProperty("parent",out var pa)&&pa.ValueKind==JsonValueKind.Object){x.ParentIssueId=S(pa,"id");x.ParentIssueKey=S(pa,"key");}else{x.ParentIssueId=null;x.ParentIssueKey=null;}if(f.TryGetProperty("resolution",out var re)&&re.ValueKind==JsonValueKind.Object){x.ResolutionId=S(re,"id");x.ResolutionName=S(re,"name");}else{x.ResolutionId=null;x.ResolutionName=null;}x.DueDate=D(f,"duedate");x.ResolutionDate=D(f,"resolutiondate");x.JiraCreatedAt=D(f,"created");x.JiraUpdatedAt=D(f,"updated");if(f.TryGetProperty("timetracking",out var tt)&&tt.ValueKind==JsonValueKind.Object){x.OriginalEstimateSeconds=L(tt,"originalEstimateSeconds");x.RemainingEstimateSeconds=L(tt,"remainingEstimateSeconds");x.TimeSpentSeconds=L(tt,"timeSpentSeconds");}if(!string.IsNullOrWhiteSpace(sp)&&f.TryGetProperty(sp,out var spe)&&spe.ValueKind==JsonValueKind.Number&&spe.TryGetDecimal(out var n))x.StoryPoints=n;else x.StoryPoints=null;x.SyncedAt=now;}
 private static void Person(JsonElement f,string name,out string? id,out string? display){id=null;display=null;if(f.TryGetProperty(name,out var p)&&p.ValueKind==JsonValueKind.Object){id=S(p,"accountId");display=S(p,"displayName");}}
 private static string? S(JsonElement e,string n)=>e.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.String?p.GetString():null;private static bool B(JsonElement e,string n)=>e.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.True;private static long? L(JsonElement e,string n)=>e.TryGetProperty(n,out var p)&&p.TryGetInt64(out var v)?v:null;private static DateTimeOffset? D(JsonElement e,string n)=>e.TryGetProperty(n,out var p)&&p.ValueKind==JsonValueKind.String&&DateTimeOffset.TryParse(p.GetString(),out var d)?d:null;private static string Safe(string m)=>m.Length<=1000?m:m[..1000];
}
