using System.Security.Cryptography; using System.Text; using System.Text.Json; using Microsoft.EntityFrameworkCore; using Microsoft.AspNetCore.WebUtilities; using ResearchTrack.BuildingBlocks.Api.Constants; using ResearchTrack.BuildingBlocks.Api.Exceptions; using ResearchTrack.JiraService.Configuration; using ResearchTrack.JiraService.Contracts; using ResearchTrack.JiraService.Domain; using ResearchTrack.JiraService.Infrastructure; using ResearchTrack.JiraService.Persistence;
namespace ResearchTrack.JiraService.Features;
public sealed class JiraConnectionService : IJiraConnectionService
{
 private readonly IDbContextFactory<JiraDbContext> _db; private readonly JiraOptions _options; private readonly IProjectAuthorizationClient _auth; private readonly AtlassianClient _atlassian; private readonly IJiraTokenProtector _protector; private readonly IJiraSyncService _sync;
 public JiraConnectionService(IDbContextFactory<JiraDbContext> db,JiraOptions options,IProjectAuthorizationClient auth,AtlassianClient atlassian,IJiraTokenProtector protector,IJiraSyncService sync){_db=db;_options=options;_auth=auth;_atlassian=atlassian;_protector=protector;_sync=sync;}
 public async Task<JiraAuthUrlResponse> StartAsync(Guid userId,Guid projectId,CancellationToken ct){await _auth.EnsureCanManageAsync(projectId,ct); ValidateConfig(); await using var db=await _db.CreateDbContextAsync(ct); if(await db.JiraConnections.AnyAsync(x=>x.ResearchProjectId==projectId,ct)) throw Bad("Jira is already connected for this project."); var raw=Opaque(); db.JiraOAuthStates.Add(new(){Id=Guid.NewGuid(),StateHash=Hash(raw),ResearchProjectId=projectId,SupervisorUserId=userId,CreatedAt=DateTimeOffset.UtcNow,ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(Math.Max(1,_options.OAuthStateTtlMinutes))}); await db.SaveChangesAsync(ct); var state=$"{raw}:{projectId:D}"; var q=new Dictionary<string,string?>{{"audience",_options.Audience},{"client_id",_options.ClientId},{"scope",NormalizeScope(_options.Scope)},{"redirect_uri",_options.RedirectUri},{"state",state},{"response_type","code"},{"prompt","consent"}}; return new(QueryHelpers.AddQueryString(_options.AuthorizationUrl,q)); }
 public async Task<JiraOAuthCompleteResponse> CompleteOAuthAsync(Guid userId,JiraOAuthCompleteRequest request,CancellationToken ct){ if(!string.IsNullOrWhiteSpace(request.SelectionToken)) return await SelectWorkspaceAsync(userId,request.SelectionToken!,request.SelectedCloudId,ct); if(!string.IsNullOrWhiteSpace(request.Error)) throw Bad(string.IsNullOrWhiteSpace(request.ErrorDescription)?"Jira authorization was denied or failed.":request.ErrorDescription!); if(string.IsNullOrWhiteSpace(request.Code)||string.IsNullOrWhiteSpace(request.State)) throw Bad("Jira OAuth callback is incomplete."); var parts=request.State.Split(':',2); if(parts.Length!=2||!Guid.TryParse(parts[1],out var projectId)) throw Bad("Jira OAuth state is invalid."); await _auth.EnsureCanManageAsync(projectId,ct); await using var db=await _db.CreateDbContextAsync(ct); var hash=Hash(parts[0]); var state=await db.JiraOAuthStates.SingleOrDefaultAsync(x=>x.StateHash==hash&&x.ResearchProjectId==projectId&&x.SupervisorUserId==userId,ct); if(state is null||state.UsedAt is not null||state.ExpiresAt<=DateTimeOffset.UtcNow) throw Bad("Jira OAuth state is invalid or expired."); state.UsedAt=DateTimeOffset.UtcNow; var token=await _atlassian.ExchangeCodeAsync(request.Code,ct); var workspaces=await _atlassian.GetWorkspacesAsync(token.AccessToken,ct); var selectionRaw=Opaque(); var selection=new JiraOAuthSelection{Id=Guid.NewGuid(),SelectionTokenHash=Hash(selectionRaw),ResearchProjectId=projectId,SupervisorUserId=userId,AccessTokenProtected=_protector.Protect(token.AccessToken),RefreshTokenProtected=string.IsNullOrWhiteSpace(token.RefreshToken)?null:_protector.Protect(token.RefreshToken),TokenExpiresAt=token.ExpiresAt,Scope=token.Scope,WorkspacesJson=JsonSerializer.Serialize(workspaces),CreatedAt=DateTimeOffset.UtcNow,ExpiresAt=DateTimeOffset.UtcNow.AddMinutes(Math.Max(1,_options.SelectionTtlMinutes))}; db.JiraOAuthSelections.Add(selection); await db.SaveChangesAsync(ct); if(workspaces.Count==1) return await SelectWorkspaceCoreAsync(db,selection,selectionRaw,workspaces[0].CloudId,ct); return new(projectId,true,false,selectionRaw,workspaces,Array.Empty<JiraProjectOption>(),null); }
 private async Task<JiraOAuthCompleteResponse> SelectWorkspaceAsync(Guid userId,string selectionToken,string? cloudId,CancellationToken ct){if(string.IsNullOrWhiteSpace(cloudId))throw Bad("Select a Jira workspace to continue."); await using var db=await _db.CreateDbContextAsync(ct); var s=await ValidSelectionAsync(db,userId,selectionToken,ct); await _auth.EnsureCanManageAsync(s.ResearchProjectId,ct); return await SelectWorkspaceCoreAsync(db,s,selectionToken,cloudId,ct);}
 private async Task<JiraOAuthCompleteResponse> SelectWorkspaceCoreAsync(JiraDbContext db,JiraOAuthSelection s,string raw,string cloudId,CancellationToken ct){var workspaces=JsonSerializer.Deserialize<List<JiraWorkspaceOption>>(s.WorkspacesJson)??[];var workspace=workspaces.SingleOrDefault(x=>x.CloudId==cloudId)??throw Bad("The selected Jira workspace is not authorized."); s.SelectedCloudId=cloudId; await db.SaveChangesAsync(ct); var projects=await _atlassian.GetProjectsAsync(_protector.Unprotect(s.AccessTokenProtected),cloudId,ct); return new(s.ResearchProjectId,false,true,raw,Array.Empty<JiraWorkspaceOption>(),projects,workspace.WorkspaceName);}
 public async Task<JiraBoardListResponse> GetBoardsAsync(Guid userId,Guid projectId,string selectionToken,string jiraProjectId,CancellationToken ct){await _auth.EnsureCanManageAsync(projectId,ct); await using var db=await _db.CreateDbContextAsync(ct);var s=await ValidSelectionAsync(db,userId,selectionToken,ct);if(s.ResearchProjectId!=projectId||string.IsNullOrWhiteSpace(s.SelectedCloudId))throw Bad("Jira selection session is invalid.");var projects=await _atlassian.GetProjectsAsync(_protector.Unprotect(s.AccessTokenProtected),s.SelectedCloudId,ct);var p=projects.SingleOrDefault(x=>x.Id==jiraProjectId)??throw Bad("The selected Jira project is not accessible.");return new(await _atlassian.GetBoardsAsync(_protector.Unprotect(s.AccessTokenProtected),s.SelectedCloudId,p.Key,ct));}
 public async Task<JiraConnectionResponse> LinkAsync(Guid userId,Guid projectId,LinkJiraProjectRequest request,CancellationToken ct){await _auth.EnsureCanManageAsync(projectId,ct); await using var db=await _db.CreateDbContextAsync(ct);if(await db.JiraConnections.AnyAsync(x=>x.ResearchProjectId==projectId,ct))throw Bad("Jira is already connected for this project.");var s=await ValidSelectionAsync(db,userId,request.SelectionToken,ct);if(s.ResearchProjectId!=projectId||string.IsNullOrWhiteSpace(s.SelectedCloudId))throw Bad("Jira selection session is invalid.");var token=_protector.Unprotect(s.AccessTokenProtected);var projects=await _atlassian.GetProjectsAsync(token,s.SelectedCloudId,ct);var p=projects.SingleOrDefault(x=>x.Id==request.JiraProjectId)??throw Bad("The selected Jira project is not accessible.");JiraBoardOption? board=null;if(request.JiraBoardId.HasValue){var boards=await _atlassian.GetBoardsAsync(token,s.SelectedCloudId,p.Key,ct);board=boards.SingleOrDefault(x=>x.Id==request.JiraBoardId.Value)??throw Bad("The selected Jira board does not belong to this Jira project.");}var workspaces=JsonSerializer.Deserialize<List<JiraWorkspaceOption>>(s.WorkspacesJson)??[];var w=workspaces.Single(x=>x.CloudId==s.SelectedCloudId);var now=DateTimeOffset.UtcNow;var c=new JiraConnection{Id=Guid.NewGuid(),ResearchProjectId=projectId,CloudId=w.CloudId,WorkspaceName=w.WorkspaceName,WorkspaceUrl=w.WorkspaceUrl,JiraProjectId=p.Id,JiraProjectKey=p.Key,JiraProjectName=p.Name,JiraBoardId=board?.Id,JiraBoardName=board?.Name,JiraBoardType=board?.Type,AccessTokenProtected=s.AccessTokenProtected,RefreshTokenProtected=s.RefreshTokenProtected,TokenExpiresAt=s.TokenExpiresAt,Scope=s.Scope,ConnectedByUserId=userId,ConnectedAt=now,UpdatedAt=now,SyncStatus="PENDING"};db.JiraConnections.Add(c);s.UsedAt=now;await db.SaveChangesAsync(ct);try{await _sync.SynchronizeAsync(projectId,ct);}catch{ /* Connection remains valid; sync state records the failure and manual refresh can retry. */ }return await GetConnectionAsync(projectId,ct) ?? Map(c);}
 public async Task DisconnectAsync(Guid userId,Guid projectId,CancellationToken ct){await _auth.EnsureCanManageAsync(projectId,ct);await using var db=await _db.CreateDbContextAsync(ct);var c=await db.JiraConnections.SingleOrDefaultAsync(x=>x.ResearchProjectId==projectId,ct)??throw Bad("Jira is not connected for this project.");var issueIds=await db.JiraIssues.Where(x=>x.ResearchProjectId==projectId).Select(x=>x.Id).ToListAsync(ct);db.JiraIssueSprints.RemoveRange(db.JiraIssueSprints.Where(x=>issueIds.Contains(x.JiraIssueId)));db.JiraIssues.RemoveRange(db.JiraIssues.Where(x=>x.ResearchProjectId==projectId));db.JiraSprints.RemoveRange(db.JiraSprints.Where(x=>x.ResearchProjectId==projectId));db.JiraConnections.Remove(c);await db.SaveChangesAsync(ct);}
 public Task StartAuthorizationCheckOnly(Guid projectId,CancellationToken ct)=>_auth.EnsureCanManageAsync(projectId,ct);
 public async Task<JiraConnectionResponse?> GetConnectionAsync(Guid projectId,CancellationToken ct){await using var db=await _db.CreateDbContextAsync(ct);var c=await db.JiraConnections.AsNoTracking().SingleOrDefaultAsync(x=>x.ResearchProjectId==projectId,ct);return c is null?null:Map(c);}
 private static JiraConnectionResponse Map(JiraConnection c)=>new(true,c.ResearchProjectId,c.WorkspaceName,c.WorkspaceUrl,c.JiraProjectId,c.JiraProjectKey,c.JiraProjectName,c.JiraBoardId,c.JiraBoardName,c.JiraBoardType,c.SyncStatus,c.LastSyncedAt,c.ConnectedAt);
 private async Task<JiraOAuthSelection> ValidSelectionAsync(JiraDbContext db,Guid userId,string raw,CancellationToken ct){var h=Hash(raw);var s=await db.JiraOAuthSelections.SingleOrDefaultAsync(x=>x.SelectionTokenHash==h&&x.SupervisorUserId==userId,ct);if(s is null||s.UsedAt is not null||s.ExpiresAt<=DateTimeOffset.UtcNow)throw Bad("Jira selection session is invalid or expired.");return s;}
 private void ValidateConfig(){if(string.IsNullOrWhiteSpace(_options.ClientId)||string.IsNullOrWhiteSpace(_options.ClientSecret)||string.IsNullOrWhiteSpace(_options.RedirectUri)||_options.ClientId=="CHANGE_ME"||_options.ClientSecret=="CHANGE_ME")throw new ApiException(503,ErrorCodes.DependencyUnavailable,"Jira OAuth is not fully configured.");}
 private static string NormalizeScope(string value){var set=value.Split(' ',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).ToHashSet(StringComparer.Ordinal);set.Add("offline_access");return string.Join(' ',set);}
 private static string Opaque()=>WebEncoders.Base64UrlEncode(RandomNumberGenerator.GetBytes(32));private static string Hash(string v)=>Convert.ToBase64String(SHA256.HashData(Encoding.UTF8.GetBytes(v)));private static ApiException Bad(string m)=>new(400,ErrorCodes.ValidationError,m);
}
