using Microsoft.EntityFrameworkCore;
using ResearchTrack.BuildingBlocks.Api.Constants;
using ResearchTrack.BuildingBlocks.Api.Exceptions;
using ResearchTrack.JiraService.Contracts;
using ResearchTrack.JiraService.Infrastructure;
using ResearchTrack.JiraService.Persistence;
namespace ResearchTrack.JiraService.Features;
public interface IJiraIssueQueryService { Task<JiraIssueListResponse> GetIssuesAsync(Guid projectId,CancellationToken ct); Task<JiraHealthResponse> GetHealthAsync(Guid projectId,CancellationToken ct); }
public sealed class JiraIssueQueryService : IJiraIssueQueryService
{
 private readonly IDbContextFactory<JiraDbContext> _db;private readonly IProjectAuthorizationClient _auth;
 public JiraIssueQueryService(IDbContextFactory<JiraDbContext> db,IProjectAuthorizationClient auth){_db=db;_auth=auth;}
 public async Task<JiraIssueListResponse> GetIssuesAsync(Guid projectId,CancellationToken ct){await _auth.EnsureCanAccessAsync(projectId,ct);await using var db=await _db.CreateDbContextAsync(ct);var c=await db.JiraConnections.AsNoTracking().SingleOrDefaultAsync(x=>x.ResearchProjectId==projectId,ct)??throw new ApiException(404,ErrorCodes.NotFound,"Jira is not connected for this project.");var rows=await db.JiraIssues.AsNoTracking().Where(x=>x.ResearchProjectId==projectId).OrderBy(x=>x.IssueKey).Select(x=>new JiraIssueResponse(x.IssueKey,x.Summary,x.IssueTypeName,x.IsSubtask,x.StatusName,x.StatusCategoryKey,x.PriorityName,x.AssigneeAccountId,x.AssigneeDisplayName,x.StoryPoints,x.ParentIssueKey,x.DescriptionJson,x.DueDate,x.JiraCreatedAt,x.JiraUpdatedAt)).ToListAsync(ct);var s=Summary(rows.Select(x=>x.StatusCategory).ToList());return new(rows,new(rows.Count,s.todo,s.progress,s.done),new(c.SyncStatus,c.LastSyncedAt,c.LastSyncError));}
 public async Task<JiraHealthResponse> GetHealthAsync(Guid projectId,CancellationToken ct){await _auth.EnsureCanAccessAsync(projectId,ct);await using var db=await _db.CreateDbContextAsync(ct);var c=await db.JiraConnections.AsNoTracking().SingleOrDefaultAsync(x=>x.ResearchProjectId==projectId,ct)??throw new ApiException(404,ErrorCodes.NotFound,"Jira is not connected for this project.");var issues=await db.JiraIssues.AsNoTracking().Where(x=>x.ResearchProjectId==projectId).Select(x=>new{x.StatusCategoryKey,x.IssueTypeName,x.PriorityName,x.DueDate,x.ResolutionDate}).ToListAsync(ct);var s=Summary(issues.Select(x=>x.StatusCategoryKey).ToList());var total=issues.Count;var open=s.todo+s.progress;var overdue=issues.Count(x=>x.DueDate<DateTimeOffset.UtcNow&&!Done(x.StatusCategoryKey));var high=issues.Count(x=>!Done(x.StatusCategoryKey)&&(string.Equals(x.PriorityName,"Highest",StringComparison.OrdinalIgnoreCase)||string.Equals(x.PriorityName,"High",StringComparison.OrdinalIgnoreCase)));var types=issues.GroupBy(x=>x.IssueTypeName).OrderByDescending(g=>g.Count()).Select(g=>new JiraTypeDistributionItemResponse(g.Key,g.Count())).ToList();var bugs=issues.Count(x=>string.Equals(x.IssueTypeName,"Bug",StringComparison.OrdinalIgnoreCase));return new(total==0?0:(int)Math.Round(100d*s.done/total),open,overdue,high,new(s.todo,s.progress,s.done),types,total==0?0d:(double)bugs/total,c.LastSyncedAt);}
 private static (int todo,int progress,int done) Summary(IReadOnlyList<string?> values){var done=values.Count(Done);var progress=values.Count(x=>string.Equals(x,"indeterminate",StringComparison.OrdinalIgnoreCase)||string.Equals(x,"in_progress",StringComparison.OrdinalIgnoreCase));return(values.Count-done-progress,progress,done);}
 private static bool Done(string? x)=>string.Equals(x,"done",StringComparison.OrdinalIgnoreCase);
}
