global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'researchtrack-services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'gateway:8080'
          - 'auth:8080'
          - 'project:8080'
          - 'github:8080'
          - 'jira:8080'
          - 'meeting:8080'
          - 'submission:8080'