// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchTrack.AuthService.Domain;
using ResearchTrack.AuthService.Persistence;

#nullable disable

namespace ResearchTrack.AuthService.Persistence.Migrations;

[DbContext(typeof(AuthDbContext))]
partial class AuthDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("ResearchTrack.AuthService.Domain.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("char(36)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime(6)");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(320)
                .HasColumnType("varchar(320)");

            b.Property<string>("FirstName")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("varchar(500)");

            b.Property<string>("LastName")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("varchar(500)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(1024)
                .HasColumnType("varchar(1024)");

            b.Property<string>("RegistrationNumber")
                .HasMaxLength(100)
                .HasColumnType("varchar(100)");

            b.Property<UserRole>("Role")
                .HasConversion<string>()
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("varchar(32)");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("datetime(6)");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique()
                .HasDatabaseName("ux_users_email");

            b.HasIndex("RegistrationNumber")
                .IsUnique()
                .HasDatabaseName("ux_users_registration_number");

            b.ToTable("users", (string)null);
        });
#pragma warning restore 612, 618
    }
}
