// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchTrack.JiraService.Persistence;

#nullable disable

namespace ResearchTrack.JiraService.Persistence.Migrations
{
    [DbContext(typeof(JiraDbContext))]
    [Migration("20260919115941_AddJiraProjectLinking")]
    partial class AddJiraProjectLinking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessTokenProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CloudId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ConnectedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("JiraBoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("JiraBoardName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("JiraBoardType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("JiraProjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("JiraProjectKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("JiraProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RefreshTokenProtected")
                        .HasColumnType("text");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scope")
                        .HasColumnType("longtext");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("WorkspaceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchProjectId")
                        .IsUnique();

                    b.ToTable("jira_connections", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraOAuthSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessTokenProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RefreshTokenProtected")
                        .HasColumnType("text");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scope")
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedCloudId")
                        .HasColumnType("longtext");

                    b.Property<string>("SelectionTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("SupervisorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WorkspacesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SelectionTokenHash")
                        .IsUnique();

                    b.ToTable("jira_oauth_selections", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("SupervisorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("StateHash")
                        .IsUnique();

                    b.HasIndex("ResearchProjectId", "SupervisorUserId");

                    b.ToTable("jira_oauth_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
