// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchTrack.JiraService.Persistence;

#nullable disable

namespace ResearchTrack.JiraService.Persistence.Migrations
{
    [DbContext(typeof(JiraDbContext))]
    partial class JiraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessTokenProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CloudId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ConnectedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("JiraBoardId")
                        .HasColumnType("bigint");

                    b.Property<string>("JiraBoardName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("JiraBoardType")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("JiraProjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("JiraProjectKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("JiraProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("LastWebhookAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshTokenProtected")
                        .HasColumnType("text");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scope")
                        .HasColumnType("longtext");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("WebhookExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("WebhookId")
                        .HasColumnType("bigint");

                    b.Property<string>("WebhookStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("WorkspaceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchProjectId")
                        .IsUnique();

                    b.ToTable("jira_connections", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraOAuthSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AccessTokenProtected")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RefreshTokenProtected")
                        .HasColumnType("text");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Scope")
                        .HasColumnType("longtext");

                    b.Property<string>("SelectedCloudId")
                        .HasColumnType("longtext");

                    b.Property<string>("SelectionTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("SupervisorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("TokenExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WorkspacesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SelectionTokenHash")
                        .IsUnique();

                    b.ToTable("jira_oauth_selections", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ResearchProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("SupervisorUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("StateHash")
                        .IsUnique();

                    b.HasIndex("ResearchProjectId", "SupervisorUserId");

                    b.ToTable("jira_oauth_states", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraIssue", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("char(36)");
                    b.Property<string>("AssigneeAccountId").HasColumnType("longtext"); b.Property<string>("AssigneeDisplayName").HasMaxLength(255).HasColumnType("varchar(255)");
                    b.Property<string>("DescriptionJson").HasColumnType("longtext"); b.Property<DateTimeOffset?>("DueDate").HasColumnType("datetime"); b.Property<bool>("IsSubtask").HasColumnType("tinyint(1)");
                    b.Property<string>("IssueKey").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<string>("IssueTypeId").HasColumnType("longtext"); b.Property<string>("IssueTypeName").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<Guid>("JiraConnectionId").HasColumnType("char(36)"); b.Property<DateTimeOffset?>("JiraCreatedAt").HasColumnType("datetime"); b.Property<string>("JiraIssueId").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)"); b.Property<DateTimeOffset?>("JiraUpdatedAt").HasColumnType("datetime");
                    b.Property<long?>("OriginalEstimateSeconds").HasColumnType("bigint"); b.Property<string>("ParentIssueId").HasColumnType("longtext"); b.Property<string>("ParentIssueKey").HasColumnType("longtext"); b.Property<string>("PriorityId").HasColumnType("longtext"); b.Property<string>("PriorityName").HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<long?>("RemainingEstimateSeconds").HasColumnType("bigint"); b.Property<string>("ReporterAccountId").HasColumnType("longtext"); b.Property<string>("ReporterDisplayName").HasMaxLength(255).HasColumnType("varchar(255)"); b.Property<Guid>("ResearchProjectId").HasColumnType("char(36)"); b.Property<DateTimeOffset?>("ResolutionDate").HasColumnType("datetime"); b.Property<string>("ResolutionId").HasColumnType("longtext"); b.Property<string>("ResolutionName").HasColumnType("longtext");
                    b.Property<string>("StatusCategoryId").HasColumnType("longtext"); b.Property<string>("StatusCategoryKey").HasMaxLength(64).HasColumnType("varchar(64)"); b.Property<string>("StatusCategoryName").HasColumnType("longtext"); b.Property<string>("StatusId").HasColumnType("longtext"); b.Property<string>("StatusName").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)"); b.Property<decimal?>("StoryPoints").HasPrecision(12,2).HasColumnType("decimal(12,2)"); b.Property<string>("Summary").IsRequired().HasMaxLength(1024).HasColumnType("varchar(1024)"); b.Property<DateTimeOffset>("SyncedAt").HasColumnType("datetime"); b.Property<long?>("TimeSpentSeconds").HasColumnType("bigint");
                    b.HasKey("Id"); b.HasIndex("JiraConnectionId"); b.HasIndex("ResearchProjectId"); b.HasIndex("ResearchProjectId","IssueKey"); b.HasIndex("ResearchProjectId","JiraIssueId").IsUnique(); b.HasIndex("ResearchProjectId","StatusCategoryKey"); b.ToTable("jira_issues",(string)null);
                });
            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraSprint", b =>
                { b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("char(36)"); b.Property<DateTimeOffset?>("CompleteDate").HasColumnType("datetime"); b.Property<DateTimeOffset?>("EndDate").HasColumnType("datetime"); b.Property<string>("Goal").HasMaxLength(2048).HasColumnType("varchar(2048)"); b.Property<long>("JiraBoardId").HasColumnType("bigint"); b.Property<Guid>("JiraConnectionId").HasColumnType("char(36)"); b.Property<long>("JiraSprintId").HasColumnType("bigint"); b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)"); b.Property<Guid>("ResearchProjectId").HasColumnType("char(36)"); b.Property<DateTimeOffset?>("StartDate").HasColumnType("datetime"); b.Property<string>("State").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)"); b.Property<DateTimeOffset>("SyncedAt").HasColumnType("datetime"); b.HasKey("Id"); b.HasIndex("JiraConnectionId"); b.HasIndex("ResearchProjectId","JiraSprintId").IsUnique(); b.ToTable("jira_sprints",(string)null); });
            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraIssueSprint", b =>
                { b.Property<Guid>("JiraIssueId").HasColumnType("char(36)"); b.Property<Guid>("JiraSprintId").HasColumnType("char(36)"); b.HasKey("JiraIssueId","JiraSprintId"); b.HasIndex("JiraSprintId"); b.ToTable("jira_issue_sprints",(string)null); });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraSyncJob", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("char(36)");
                    b.Property<int>("AttemptCount").HasColumnType("int");
                    b.Property<DateTimeOffset>("AvailableAt").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("datetime(6)");
                    b.Property<string>("EntityId").HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("LastError").HasColumnType("text");
                    b.Property<string>("Reason").IsRequired().HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<Guid>("ResearchProjectId").HasColumnType("char(36)");
                    b.Property<DateTimeOffset>("RequestedAt").HasColumnType("datetime(6)");
                    b.Property<string>("Scope").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.Property<DateTimeOffset?>("StartedAt").HasColumnType("datetime(6)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("ResearchProjectId", "Status");
                    b.HasIndex("Status", "AvailableAt");
                    b.ToTable("jira_sync_jobs", (string)null);
                });

            modelBuilder.Entity("ResearchTrack.JiraService.Domain.JiraWebhookEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("char(36)");
                    b.Property<int>("AttemptCount").HasColumnType("int");
                    b.Property<string>("CloudId").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("DeliveryId").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("IssueKey").HasMaxLength(64).HasColumnType("varchar(64)");
                    b.Property<string>("JiraIssueId").HasMaxLength(128).HasColumnType("varchar(128)");
                    b.Property<string>("LastError").HasColumnType("text");
                    b.Property<string>("PayloadJson").IsRequired().HasColumnType("longtext");
                    b.Property<DateTimeOffset?>("ProcessedAt").HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("ReceivedAt").HasColumnType("datetime(6)");
                    b.Property<Guid?>("ResearchProjectId").HasColumnType("char(36)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("varchar(32)");
                    b.HasKey("Id");
                    b.HasIndex("DeliveryId").IsUnique();
                    b.HasIndex("ResearchProjectId");
                    b.HasIndex("Status", "ReceivedAt");
                    b.ToTable("jira_webhook_events", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
